### ISSUE TITLE
Grappling

### ISSUE THREAD

**Issue by scottkeeney** [danielrcollins1/OED-Expanded#1]
Grappling is mentioned in a couple of the monster entries but I don't see a house rule for it. I don't recall from your blog or YouTube if you're using Gary's rules from the The Strategic Review? I've found that to work well (at least at the low/mid levels at which I've actually used them). So, proposed addition related to Unarmed Combat (and maybe put that and this at the end of the Combat section?)...
 
Grappling: Attackers (those attempting to restrain their opponent) roll as normal. The successful attackers and the defender both roll a number of dice equal to their total hit dice. On a tie, both parties struggle, neither able to take advantage. Defenders that win throw off the successful attackers,stunning them for a round. If the attackers win, the defender is restrained and captured.

**Comment by danielrcollins1** [comment]
Thanks for this reminder! We've recently add a simple grappling rule in the Gameplay chapter: Not 100% as you suggested -- there's a roll to hit and then a 1d6 + Str bonus opposed roll to see if someone gets grappled. (Hit dice convert to Str bonus here by halving.) That's what I've done for some time, hope that's workable for you?

https://github.com/danielrcollins1/OED-Expanded/blob/main/gameplay.md
