### ISSUE TITLE
Feature Request: Table of Contents and page numbers

### ISSUE THREAD

**Issue by nk3nny** [danielrcollins1/OED-Expanded#2]
The ruleset matches the bare bones style wonderfully, but a table of contents and page numbers would make navigating the rule and referencing them in other discussions much easier. 

A PDF alternative would equally be welcome, as I found the .odt (perhaps due to my using of Word and default Euro page sizes) displayed with irregular cuts.

**Comment by danielrcollins1** [comment]
Restructuring how the document is generated -- still a lot of prettification work to go. But we could auto-generate a table of contents with page numbers as of the 0.0.2 release. You can get that here -- https://github.com/danielrcollins1/OED-Expanded/releases/tag/0.0.2

Thanks for the suggestion!
